language: ruby
cache: bundler
rvm:
  - 2.6.6
dist: bionic
addons:
  apt:
    packages:
      - chromium-browser
services:
  - postgresql
branches:
  except:
    - /^depfu/.*$/
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v $(tail -n 1 Gemfile.lock)
notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "chat.freenode.net#osem"
    on_success: change
    on_failure: change
before_script:
  - RAILS_ENV=test bundle exec rake db:bootstrap --trace
  - RAILS_ENV=test bundle exec bin/rails webdrivers:chromedriver:update
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
script:
  - "bin/travis_script.sh $TEST_SUITE"
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l Ruby -r coverage/coverage.xml

jobs:
  fast_finish: false
  include:
    - stage: finalize
      script: bash <(curl -Ls https://coverage.codacy.com/get.sh) final

env:
  global:
    - OSEM_DB_ADAPTER=sqlite3
    - OSEM_DB_HOST=''
    - OSEM_DB_PORT=''
    - OSEM_DB_NAME='osem_test'
  jobs:
    - TEST_SUITE=ability
    - TEST_SUITE=features
    - TEST_SUITE=models
    - TEST_SUITE=controllers
    - TEST_SUITE=rest
