language: ruby
cache: bundler
rvm:
  - 2.6.6
dist: bionic
addons:
  apt:
    packages:
      - chromium-browser
services:
  - postgresql
branches:
  except:
    - /^depfu/.*$/
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v $(tail -n 1 Gemfile.lock)
notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "chat.freenode.net#osem"
    on_success: change
    on_failure: change
before_script:
  # install CodeClimate test reporter and tell it we are starting a test run
  # - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  # - chmod +x $CCTR
  # - $CCTR before-build
  - RAILS_ENV=test bundle exec rake db:bootstrap --trace
  - RAILS_ENV=test bundle exec bin/rails webdrivers:chromedriver:update
script:
  - "bin/travis_script.sh $TEST_SUITE"
  # TODO Get this working.
  # -  $CCTR format-coverage -t simplecov --output coverage/codeclimate.$SUITE.json
# after_script:
  # combine coverage from all suites, and upload3 to CodeClimate
  # - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
  # - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    - OSEM_DB_ADAPTER=sqlite3
    - OSEM_DB_HOST=''
    - OSEM_DB_PORT=''
    - OSEM_DB_NAME='osem_test'
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER
    - CCTR=./cc-test-reporter
  matrix:
    - TEST_SUITE=ability
    - TEST_SUITE=features
    - TEST_SUITE=models
    - TEST_SUITE=controllers
    - TEST_SUITE=rest
matrix:
  fast_finish: false
