name: Specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    env:
      OSEM_RUBY_VERSION: 2.6.6
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec haml-lint app/views
  spec:
    runs-on: ubuntu-latest
    name: spec
    env:
      OSEM_DB_ADAPTER: sqlite3
      OSEM_RUBY_VERSION: 2.6.6
      RAILS_ENV: test
    strategy:
      matrix:
        suite: [models, features, controllers, ability, leftovers]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Prepare spec
        run: |
          rm -f osem_test osem_development
          bundle exec rake db:setup --trace
          bundle exec bin/rails webdrivers:chromedriver:update
      - name: spec/${{ matrix.suite }}
        if: matrix.suite != 'leftovers'
        run: bundle exec rspec spec/${{ matrix.suite }}
      - name: spec/leftovers
        if: matrix.suite == 'leftovers'
        run: bundle exec rspec --exclude-pattern "spec/{models, features, controllers, ability}/**/*_spec.rb, spec/datatables/**/*_spec.rb"
      - name: coverage upload ${{ matrix.suite }}
        uses: codacy/codacy-coverage-reporter-action@master
        if: github.ref == 'refs/heads/master'
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/coverage.xml
